/*
-- Query: select * from dept
LIMIT 0, 1000

-- Date: 2022-05-13 02:08
*/
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (20,'IT Sales');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (10,'IT Tech');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (30,'HRBP');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (40,'Sales Dept - Buisness');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (50,'Cloud Infra');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (60,'Hr Admin');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (70,'IT Admin');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (90,'R&D');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (100,'Clerk');
INSERT INTO `dept` (`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES (110,'Analyst');

